### ISSUE TITLE
error that Cohen's d is paired for one sample t-test/effectsize

### ISSUE THREAD

**Issue by einGlasRotwein** [m-Py/prmisc#26]
When printing a one-sample t-test + effect size estimate using `print_ttest()`, the following error is thrown: `t-test is not paired, but Cohens d is paired`

See:

```
library(effectsize)
library(prmisc)

my_data <- rnorm(100, .2)
my_ttest <- t.test(my_data)
my_cohen <- cohens_d(my_data)

print_ttest(my_ttest, my_cohen)
```

That is because `print_ttest()` checks whether the attribute "paired" for the Cohens d object is `FALSE`. However, the attribute is `TRUE` for single samples. 

My suggestion would be to adjust the check for the t-test object so it also covers the single sample case, but wanted to discuss first whether that would be desired behaviour.

**Comment by m-Py** [comment]
I see. Seems to me quite questionable that the attribute `paired` is `TRUE` because that is misleading. I suppose that they use the computation for a one sided t test for the paired Cohen's d and therefore set `paired` to `TRUE`, but the other way around does not work. 

Still, we should deal with that.

**Comment by einGlasRotwein** [comment]
Raised the issue at `effectsize` - it's fixed on their end now, see: https://github.com/easystats/effectsize/issues/645#event-13140718729

**Comment by einGlasRotwein** [comment]
Issue has been fixed in `effectsize`, see: https://github.com/easystats/effectsize/issues/645

**Comment by einGlasRotwein** [comment]
Issue has been fixed in `effectsize`, see: https://github.com/easystats/effectsize/issues/645

**Comment by m-Py** [comment]
Nice. Then we do not need to change the code here.
